ATSC_DIR=.
ENV_DIR=$ATSC_DIR/env/linux
INTERPRETER_DIR=$ENV_DIR/bin
INTERPRETER=python3
INTERPRETER_PATH=$INTERPRETER_DIR/$INTERPRETER
ATSC_SCREEN=atsc
ATSC_PID_FILE=$ATSC_DIR/atsc.pid
ATSC_LOG_FILE=$ATSC_DIR/logs/atsc.log