import os


DEFAULT_APP_STYLESHEET_PATH = 'tui/css/app.tcss'
CONTROLLER_POLL_RATE = 0.2

if os.getenv('LOOSEN_RPC_WATCHDOG'):
    RPC_CALL_DEADLINE_INITIAL = 3600.0
    RPC_CALL_DEADLINE_POLL = 3600.0
    RPC_CALL_TIMEOUT = 3600.0
else:
    RPC_CALL_DEADLINE_INITIAL = 5.0
    RPC_CALL_DEADLINE_POLL = 0.4
    RPC_CALL_TIMEOUT = 0.4
