# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: protobufs/signal.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import List

import betterproto


class SignalState(betterproto.Enum):
    DARK = 0
    STOP = 1
    CAUTION = 2
    EXTEND = 3
    GO = 4
    FYA = 5
    LS_FLASH = 6


class SignalType(betterproto.Enum):
    GENERIC = 0
    VEHICLE = 1
    PEDESTRIAN = 2


class TrafficMovement(betterproto.Enum):
    THRU = 0
    PROTECTED_TURN = 1
    PERMISSIVE_TURN = 2


@dataclass(eq=False, repr=False)
class SignalMetadata(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    field_output_ids: List[int] = betterproto.uint32_field(2)
    type: "SignalType" = betterproto.enum_field(3)
    movement: "TrafficMovement" = betterproto.enum_field(4)
    initial_state: "SignalState" = betterproto.enum_field(5)


@dataclass(eq=False, repr=False)
class Signal(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    active: bool = betterproto.bool_field(10)
    resting: bool = betterproto.bool_field(11)
    presence: bool = betterproto.bool_field(12)
    demand: bool = betterproto.bool_field(13)
    interval_time: float = betterproto.float_field(20)
    service_time: float = betterproto.float_field(21)
    state: "SignalState" = betterproto.enum_field(30)
