# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: protobufs/field_output.proto
# plugin: python-betterproto
# This file has been @generated

import betterproto
from dataclasses import dataclass


class FieldOutputState(betterproto.Enum):
    OFF = 0
    ON = 1
    FLASHING = 2


@dataclass(eq=False, repr=False)
class FieldOutputMetadata(betterproto.Message):
    id: int = betterproto.uint32_field(1)


@dataclass(eq=False, repr=False)
class FieldOutput(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    state: "FieldOutputState" = betterproto.enum_field(2)
    value: bool = betterproto.bool_field(3)
    fpm: float = betterproto.float_field(4)
