# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: atsc.proto
"""Generated protocol buffer code."""
from google.protobuf import message as _message
from google.protobuf import descriptor as _descriptor
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database


# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='atsc.proto',
  package='atsc',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\natsc.proto\x12\x04\x61tsc\">\n\nFieldState\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x1f\n\x08\x63hannels\x18\x02 \x03(\x0b\x32\r.atsc.Channel\"b\n\x07\x43hannel\x12\t\n\x01\x61\x18\x01 \x01(\x08\x12\t\n\x01\x62\x18\x02 \x01(\x08\x12\t\n\x01\x63\x18\x03 \x01(\x08\x12\x10\n\x08\x64uration\x18\x04 \x01(\x05\x12\x15\n\rinterval_time\x18\x05 \x01(\x05\x12\r\n\x05\x63\x61lls\x18\x06 \x01(\x05'
)




_FIELDSTATE = _descriptor.Descriptor(
  name='FieldState',
  full_name='atsc.FieldState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='atsc.FieldState.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='channels', full_name='atsc.FieldState.channels', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=82,
)


_CHANNEL = _descriptor.Descriptor(
  name='Channel',
  full_name='atsc.Channel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='atsc.Channel.a', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b', full_name='atsc.Channel.b', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='c', full_name='atsc.Channel.c', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration', full_name='atsc.Channel.duration', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interval_time', full_name='atsc.Channel.interval_time', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='calls', full_name='atsc.Channel.calls', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=182,
)

_FIELDSTATE.fields_by_name['channels'].message_type = _CHANNEL
DESCRIPTOR.message_types_by_name['FieldState'] = _FIELDSTATE
DESCRIPTOR.message_types_by_name['Channel'] = _CHANNEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FieldState = _reflection.GeneratedProtocolMessageType('FieldState', (_message.Message,), {
  'DESCRIPTOR' : _FIELDSTATE,
  '__module__' : 'atsc_pb2'
  # @@protoc_insertion_point(class_scope:atsc.FieldState)
  })
_sym_db.RegisterMessage(FieldState)

Channel = _reflection.GeneratedProtocolMessageType('Channel', (_message.Message,), {
  'DESCRIPTOR' : _CHANNEL,
  '__module__' : 'atsc_pb2'
  # @@protoc_insertion_point(class_scope:atsc.Channel)
  })
_sym_db.RegisterMessage(Channel)


# @@protoc_insertion_point(module_scope)
