# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: protobufs/phase.proto
# plugin: python-betterproto
# This file has been @generated

import betterproto
from .. import signal as _signal__
from typing import List
from dataclasses import dataclass


@dataclass(eq=False, repr=False)
class Phase(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    presence: bool = betterproto.bool_field(10)
    demand: bool = betterproto.bool_field(11)
    resting: bool = betterproto.bool_field(12)
    field_output_ids: List[int] = betterproto.uint32_field(20)
    signal_ids: List[int] = betterproto.uint32_field(21)
    interval_time: float = betterproto.float_field(30)
    service_time: float = betterproto.float_field(31)
    state: "_signal__.SignalState" = betterproto.enum_field(40)
