# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controller.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ontroller.proto\x12\x04\x61tsc\"\x0f\n\rStatusRequest\"\xbf\x01\n\x0eStatusResponse\x12\x1f\n\x04mode\x18\n \x01(\x0e\x32\x11.atsc.ControlMode\x12\x13\n\x0bstate_flags\x18\x14 \x01(\r\x12\x0f\n\x07plan_id\x18\x1e \x01(\r\x12\x12\n\navg_demand\x18( \x01(\x02\x12\x13\n\x0bpeek_demand\x18) \x01(\x02\x12\x0f\n\x07runtime\x18\x32 \x01(\x04\x12\x14\n\x0c\x63ontrol_time\x18\x33 \x01(\x04\x12\x16\n\x0etransfer_count\x18< \x01(\x04*m\n\x0b\x43ontrolMode\x12\x10\n\x0cMODE_UNKNOWN\x10\x00\x12\x0c\n\x08MODE_OFF\x10\n\x12\x0c\n\x08MODE_CET\x10\x14\x12\x0f\n\x0bMODE_NORMAL\x10\x1e\x12\x0c\n\x08MODE_CXT\x10(\x12\x11\n\rMODE_LS_FLASH\x10\x32\x32\x44\n\nController\x12\x36\n\tGetStatus\x12\x13.atsc.StatusRequest\x1a\x14.atsc.StatusResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'controller_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONTROLMODE._serialized_start=237
  _CONTROLMODE._serialized_end=346
  _STATUSREQUEST._serialized_start=26
  _STATUSREQUEST._serialized_end=41
  _STATUSRESPONSE._serialized_start=44
  _STATUSRESPONSE._serialized_end=235
  _CONTROLLER._serialized_start=348
  _CONTROLLER._serialized_end=416
# @@protoc_insertion_point(module_scope)
